name = "pos-saas-backend"
compatibility_date = "2024-06-01"

[[d1_databases]]
binding = "DB"
database_name = "pos-saas-database"
database_id = "your-database-id"

[kv_namespaces]
binding = "SESSIONS"
id = "your-kv-id"